// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/about/career/index.tsx";
import * as $2 from "./routes/about/career/vacancy/buhgalter.tsx";
import * as $3 from "./routes/about/career/vacancy/menedzher-po-snabzheniyu.tsx";
import * as $4 from "./routes/about/career/vacancy/menedzher.tsx";
import * as $5 from "./routes/about/career/vacancy/operator-pk.tsx";
import * as $6 from "./routes/about/defaulter.tsx";
import * as $7 from "./routes/about/index.tsx";
import * as $8 from "./routes/about/team.tsx";
import * as $9 from "./routes/blog.tsx";
import * as $10 from "./routes/brands/[url].tsx";
import * as $11 from "./routes/catalog/[url].tsx";
import * as $12 from "./routes/catalog/index.tsx";
import * as $13 from "./routes/contacts.tsx";
import * as $14 from "./routes/data/brands.ts";
import * as $15 from "./routes/data/categories.ts";
import * as $16 from "./routes/data/navCategories.ts";
import * as $17 from "./routes/data/news.ts";
import * as $18 from "./routes/data/popular-products.ts";
import * as $19 from "./routes/data/product.ts";
import * as $20 from "./routes/data/products-page.ts";
import * as $21 from "./routes/data/products-search.ts";
import * as $22 from "./routes/delivery.tsx";
import * as $23 from "./routes/index.tsx";
import * as $24 from "./routes/products/[url].tsx";
import * as $25 from "./routes/video.tsx";
import * as $$0 from "./islands/BrandsFooterList.tsx";
import * as $$1 from "./islands/CatalogItem.tsx";
import * as $$2 from "./islands/CatalogList.tsx";
import * as $$3 from "./islands/CatalogSearch.tsx";
import * as $$4 from "./islands/CategoriesNavDialog.tsx";
import * as $$5 from "./islands/CategoriesNavDropdown.tsx";
import * as $$6 from "./islands/CategoryProducts.tsx";
import * as $$7 from "./islands/CharityDropdown.tsx";
import * as $$8 from "./islands/Container.tsx";
import * as $$9 from "./islands/Dropdown.tsx";
import * as $$10 from "./islands/GeographySalesDropdown.tsx";
import * as $$11 from "./islands/HomeCategories.tsx";
import * as $$12 from "./islands/NavDropdown.tsx";
import * as $$13 from "./islands/NewsList.tsx";
import * as $$14 from "./islands/PopularProductsSlider.tsx";
import * as $$15 from "./islands/PublicLifeMedia.tsx";
import * as $$16 from "./islands/TopNewSlider.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/about/career/index.tsx": $1,
    "./routes/about/career/vacancy/buhgalter.tsx": $2,
    "./routes/about/career/vacancy/menedzher-po-snabzheniyu.tsx": $3,
    "./routes/about/career/vacancy/menedzher.tsx": $4,
    "./routes/about/career/vacancy/operator-pk.tsx": $5,
    "./routes/about/defaulter.tsx": $6,
    "./routes/about/index.tsx": $7,
    "./routes/about/team.tsx": $8,
    "./routes/blog.tsx": $9,
    "./routes/brands/[url].tsx": $10,
    "./routes/catalog/[url].tsx": $11,
    "./routes/catalog/index.tsx": $12,
    "./routes/contacts.tsx": $13,
    "./routes/data/brands.ts": $14,
    "./routes/data/categories.ts": $15,
    "./routes/data/navCategories.ts": $16,
    "./routes/data/news.ts": $17,
    "./routes/data/popular-products.ts": $18,
    "./routes/data/product.ts": $19,
    "./routes/data/products-page.ts": $20,
    "./routes/data/products-search.ts": $21,
    "./routes/delivery.tsx": $22,
    "./routes/index.tsx": $23,
    "./routes/products/[url].tsx": $24,
    "./routes/video.tsx": $25,
  },
  islands: {
    "./islands/BrandsFooterList.tsx": $$0,
    "./islands/CatalogItem.tsx": $$1,
    "./islands/CatalogList.tsx": $$2,
    "./islands/CatalogSearch.tsx": $$3,
    "./islands/CategoriesNavDialog.tsx": $$4,
    "./islands/CategoriesNavDropdown.tsx": $$5,
    "./islands/CategoryProducts.tsx": $$6,
    "./islands/CharityDropdown.tsx": $$7,
    "./islands/Container.tsx": $$8,
    "./islands/Dropdown.tsx": $$9,
    "./islands/GeographySalesDropdown.tsx": $$10,
    "./islands/HomeCategories.tsx": $$11,
    "./islands/NavDropdown.tsx": $$12,
    "./islands/NewsList.tsx": $$13,
    "./islands/PopularProductsSlider.tsx": $$14,
    "./islands/PublicLifeMedia.tsx": $$15,
    "./islands/TopNewSlider.tsx": $$16,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
