import { transformTelLink } from "./link.ts";

const data = [
  {
    lastName: "Глушков",
    firstName: "Денис",
    middleName: "Игоревич",
    post: "Генеральный директор",
    phone: "+7 (343) 288-26-88",
    email: "dir@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Дик",
    firstName: "Александра",
    middleName: "Олеговна",
    post: "Коммерческий директор",
    phone: "+7 (343) 288-26-88 (доб. 102) ",
    email: "dik@tehmet.su",
    whatsapp: "+7 (922) 174-49-79",
    icq: "",
  },
  {
    lastName: "Неводничек",
    firstName: "Марина",
    middleName: "Андреевна",
    post: "Технический директор",
    phone: "+7 (343) 302-15-83 (доб. 131) ",
    email: "study@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Манько",
    firstName: "Елена",
    middleName: "Анатольевна",
    post: "Главный бухгалтер",
    phone: "+7 (343) 302-15-83 (доб. 114)",
    email: "buh@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Глушкова",
    firstName: "Евгения",
    middleName: "Юрьевна",
    post: "Руководитель отдела персонала",
    phone: "+7 (343) 302-15-83 (доб. 116) ",
    email: "personal@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Кириллова",
    firstName: "Маргарита",
    middleName: "Александровна",
    post: "Руководитель отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 119) ",
    email: "sale1@tehmet.su",
    whatsapp: "+7 (922) 174-24-99",
    icq: "",
  },
  {
    lastName: "Брыжко",
    firstName: "Елена",
    middleName: "Глебовна",
    post: "Руководитель отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 125)",
    email: "sale7@tehmet.su",
    whatsapp: "+7 (922) 229 00 18",
    icq: "",
  },
  {
    lastName: "Крупец",
    firstName: "Александра",
    middleName: "Вячеславовна",
    post: "Руководитель отдела снабжения",
    phone: "+7 (343) 302-15-83 (доб. 108)",
    email: "snab@tehmet.su",
    whatsapp: "+7 (922) 113 41 33",
    icq: "",
  },
  {
    lastName: "Чернова",
    firstName: "Ирина",
    middleName: "Валерьевна",
    post: "Руководитель отдела маркетинга",
    phone: "+7 (343) 302-15-83 (доб. 107)",
    email: "market@tehmet.su",
    whatsapp: "+7 (922) 223 60 03",
    icq: "",
  },
  {
    lastName: "Шарапова",
    firstName: "Гульнара",
    middleName: "Зайнулловна",
    post: "Руководитель региональных продаж",
    phone: "+7 (343) 302-15-83 (доб. 136)",
    email: "sale12@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Горнушкин",
    firstName: "Геннадий",
    middleName: "Валерьевич",
    post: "Начальник склада",
    phone: "+7 (343) 302-15-83 (доб. 115)",
    email: "sklad@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Панова",
    firstName: "Елизавета",
    middleName: "Сергеевна",
    post: "Помощник генерального директора",
    phone: "+7 (343) 302-15-83 (доб. 110)",
    email: "office@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Данилова",
    firstName: "Виктория",
    middleName: "Сергеевна",
    post: "Специалист отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 121)",
    email: "sale2@tehmet.su",
    whatsapp: "+7 (922) 026 21 93",
    icq: "",
  },
  {
    lastName: "Чупраков",
    firstName: "Евгений",
    middleName: "Владимирович",
    post: "Ведущий специалист отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 106)",
    email: "frz@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Шевченко",
    firstName: "Анна",
    middleName: "Владимировна",
    post: "Специалист отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 124)",
    email: "sale4@tehmet.su",
    whatsapp: "+7 (922) 174-49-97",
    icq: "",
  },
  {
    lastName: "Лобода",
    firstName: "Александра",
    middleName: "Михайловна",
    post: "Специалист отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 113)",
    email: "sale3@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Власов",
    firstName: "Михаил",
    middleName: "Александрович",
    post: "Специалист отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 117)",
    email: "vlasov@tehmet.su",
    whatsapp: "+7 (922) 174-32-62",
    icq: "",
  },
  {
    lastName: "Якимова",
    firstName: "Ольга",
    middleName: "Владимировна",
    post: "Специалист отдела продаж",
    phone: "+7 (343) 302-15-83 (доб. 122)",
    email: "sale15@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Попович",
    firstName: "Оксана",
    middleName: "Алексеевна",
    post: "Помощник руководителя",
    phone: "+7 (343) 288-26-88 (доб.112)",
    email: "sale8@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Байбородина",
    firstName: "Алена",
    middleName: "Леонидовна",
    post: "Помощник менеджера",
    phone: "+7 (343) 302-15-83 (доб. 137)",
    email: "sale16@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Пересторонина",
    firstName: "Ольга",
    middleName: "Артуровна",
    post: "Помощник менеджера",
    phone: "+7 (343) 288-26-88 (доб.104)",
    email: "sale5@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Позднякова",
    firstName: "Людмила",
    middleName: "Николаевна",
    post: "Помощник менеджера",
    phone: "+7 (343) 288-26-88 (доб.109)",
    email: "sale10@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Власова",
    firstName: "Елизавета",
    middleName: "Валерьевна",
    post: "Специалист отдела снабжения",
    phone: "+7 (343) 288-26-88 (доб.127)",
    email: "snab3@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Медвецкая",
    firstName: "Мария",
    middleName: "Вячеславовна",
    post: "Специалист отдела снабжения",
    phone: "+7 (343) 288-26-88 (доб.123)",
    email: "snab1@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Южанина",
    firstName: "Юлия",
    middleName: "Юрьевна",
    post: "Специалист по логистике",
    phone: "+7 (343) 288-26-88 (доб.129)",
    email: "snab4@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Кротова",
    firstName: "Татьяна",
    middleName: "Вячеславовна",
    post: "Специалист отдела снабжения",
    phone: "+7 (343) 288-26-88 (доб.132)",
    email: "log1@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Архипова",
    firstName: "Анна",
    middleName: "Геннадьевна",
    post: "Бухгалтер",
    phone: "+7 (343) 288-26-88 (доб.126)",
    email: "buh4@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Тузникова",
    firstName: "Светлана",
    middleName: "Анатольевна",
    post: "Бухгалтер",
    phone: "+7 (343) 288-26-88 (доб.128)",
    email: "buh1@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Девятова",
    firstName: "Людмила",
    middleName: "Ивановна",
    post: "Бухгалтер",
    phone: "+7 (343) 288-26-88 (доб.120)",
    email: "buh3@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Усова",
    firstName: "Ольга",
    middleName: "Андреевна",
    post: "Бухгалтер",
    phone: "+7 (343) 288-26-88 (доб.118)",
    email: "buh2@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Новикова",
    firstName: "Виктория",
    middleName: "Николаевна",
    post: "Заместитель начальника склада",
    phone: "+7 (343) 288-26-88 (доб.115)",
    email: "sklad@tehmet.su",
    whatsapp: "",
    icq: "",
  },
  {
    lastName: "Суднева",
    firstName: "Татьяна",
    middleName: "Александровна",
    post: "Офис-менеджер",
    phone: "+7 (343) 288-26-88 (доб.133)",
    email: "e-mail:office@tehmet.su",
    whatsapp: "",
    icq: "",
  },
];

export const employee = () => {
  return data.map((x) => ({
    ...x,
    fio: [x.lastName, x.firstName, x.middleName].filter(Boolean).join(" "),
    io: [x.firstName, x.middleName].filter(Boolean).join(" "),
    whatsappLink: transformTelLink(x.whatsapp),
    icqLink: transformTelLink(x.icq),
    phoneLink: transformTelLink(x.phone),
    img:
      [
        x.lastName?.toLowerCase(),
        x.firstName?.toLowerCase(),
        x.middleName?.toLowerCase(),
      ]
        .filter(Boolean)
        .join("-") + ".jpg",
  }));
};
